services:
  pathways_api:
    container_name: PathwaysAPI
    env_file:
      - ../.env
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../app:/api/app
    ports:
      - "80:80"
